# Default values for acg-starwars.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 826018717787.dkr.ecr.us-east-2.amazonaws.com/starwars-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  name: starwars-service

aws:
  region: us-east-2

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
