version: 0.2

env:
  variables:
    APP: starwars-frontend
    ECR_URL: <RepoURI>
    ECR_REPO_NAME: <RepoName>

phases:
  pre_build:
    commands:
      - source `pwd`/version
      - COMMIT_ID_SHORT=`echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c1-8`
      - TAG=`echo "${MAJOR}.${MINOR}.${COMMIT_ID_SHORT}"`
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${ECR_URL}
  build:  
    commands:
      - docker build -t ${APP}:${TAG}
      - docker tag ${APP}:${TAG} ${ECR_URL}/${ECR_REPO_NAME}:${TAG}
  post_build:
    commands:
      - docker push ${ECR_URL}/${ECR_REPO_NAME}:${TAG}

      