apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-acg
  region: us-east-2
  version: "1.20"

vpc:
  cidr: 10.0.0.0/16

nodeGroups:
  - name: eks-node-group
    instanceType: t2.medium
    desiredCapacity: 2
    privateNetworking: true
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::826018717787:policy/AlbControllerPolicy
        - arn:aws:iam::826018717787:policy/ExternalDNSPolicy
