version: 0.2
env:
  parameter-store:
    SONAR_TOKEN: SONARTOKEN
    SONARORG: SONARORG
    SONAR_PROJECT_KEY: SONARPROJECTKEY
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm install -g sonarqube-scanner
  build:
    commands:
      - sonar-scanner -Dsonar.organization=$SONARORG -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io