ingress:
  internal:
    annotations: 
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internal
      alb.ingress.kubernetes.io/actions.redirect: "{\"Type\": \"redirect\", \"RedirectConfig\": {\"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
      alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80,\"HTTPS\": 443}]"
      alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=360"
    path: /
    hosts:
      - hostname: starwars-api.saska.click
        serviceName: starwars-api
        port: 80
      - hostname: starwars.saska.click
        serviceName: front-end-service-proxy
        port: 80

      
  external:
    annotations: 
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/actions.redirect: "{\"Type\": \"redirect\", \"RedirectConfig\": {\"Protocol\": \"HTTPS\", \"Port\": \"443\", \"StatusCode\": \"HTTP_301\"}}"
      alb.ingress.kubernetes.io/listen-ports: "[{\"HTTP\":80,\"HTTPS\": 443}]"
      alb.ingress.kubernetes.io/load-balancer-attributes: "idle_timeout.timeout_seconds=360"
    path: /
    hosts:
      - hostname: starwars-api.saska.click
        serviceName: starwars-api
        port: 80

      - hostname: starwars.saska.click
        serviceName: front-end-service-proxy
        port: 80
